[package]
name = "bridge-loss-emu"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
csv = "1.3.1"
netns-rs = "0.1.0"
serde = { version = "1.0.218", features = ["derive"] }
users = "0.11.0"
